name: Hello World Workflow

on:
   push:
      branches:
          -main
   pull_request:
      branches:
         -main
   workflow_dispatch:

jobs:
  hello:
     runs-on: ubuntu-latest
     steps:
        - uses: action/checkout@v3
        - name: hello world
          run: echo "Hello world"
          shell: bash
