name: Hello

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions: read-all

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      deployments: write
      contents: read
      actions: read
   steps:
        - uses: action/checkout@v3
        - name: hello world
          run: echo "Hello world"
          shell: bash
